### ISSUE TITLE
Framework resource extraction failed ?

### ISSUE THREAD

**Issue by MikeWilcoxMicrosoft** [Azure-Samples/Cognitive-Services-Vision-Solution-Templates#26]
Build results in: 

Framework resource extraction failed. Could not find a part of the path 'C:\Users\miwilcox\Documents\Vision Kit Microsoft\IOTVisualAlertSample\Cognitive-Services-Vision-Solution-Templates-master\IoTVisualAlerts\obj\ARM\Debug\Microsoft.Extensions.DependencyInjection.Abstractions\en-us\Microsoft.Extensions.DependencyInjection.Abstractions.Resources.resw'.

**Comment by CarlosP-MS** [comment]
Closing, as it seems like you got unblocked (based on the other comment).
