### ISSUE TITLE
Framework resource extraction failed. Could not find a part of the path ?

### ISSUE THREAD

**Issue by MikeWilcoxMicrosoft** [Azure-Samples/Cognitive-Services-Vision-Solution-Templates#27]
For X86 build we get the error: 

Severity	Code	Description	Project	File	Line	Suppression State	
Error		Framework resource extraction failed. Could not find a part of the path 'C:\Users\miwilcox\Documents\Vision Kit Microsoft\IOTVisualAlertSample\Cognitive-Services-Vision-Solution-Templates-master\IoTVisualAlerts\obj\x86\Debug\Microsoft.Extensions.DependencyInjection.Abstractions\en-us\Microsoft.Extensions.DependencyInjection.Abstractions.Resources.resw'.	IoTVisualAlerts

**Comment by MikeWilcoxMicrosoft** [comment]
Note we get this error 1st then the 'error framework resource extraction failed"   

1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(824,5): warning : Certificate file does not exist: IoTLearningCamera_TemporaryKey.pfx

**Comment by CarlosP-MS** [comment]
There was an incorrect file reference. It is fixed now. Thanks for flagging it.
